version: '3.8'

services:
  beer-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    networks:
      - brewery-network

networks:
  brewery-network:
    driver: bridge