version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "brewery/pom.xml" }}
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "brewery/pom.xml" }}

      - run: mvn integration-test
