name: Java CI with Maven and Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        run: mvn -B clean verify --file beer-service/pom.xml

      - name: Build Docker image
        run: docker build -t beer-service:latest -f Dockerfile .

      - name: Run Docker container for testing
        run: |
          docker run -d --name beer-service-test -p 8080:8080 beer-service:latest
          sleep 10
          docker ps
          docker logs beer-service-test
          docker stop beer-service-test